version: '3.8'

services:
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SERVICE_NAME=user-service
    networks:
      - quiz-network

  quiz-service:
    build: ./services/quiz-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SERVICE_NAME=quiz-service
    networks:
      - quiz-network

  results-service:
    build: ./services/results-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - SERVICE_NAME=results-service
      - QUIZ_SERVICE_URL=http://quiz-service:3002
    networks:
      - quiz-network


networks:
  quiz-network:
    driver: bridge